import { afterEach, describe, expect, it } from 'vitest';
import { randomUUID } from 'node:crypto';
import { InMemoryOperationsRepository } from '../src/adapters/in-memory-repository.js';
import { LocalCoordination, seedLocal, bedId, NURSE } from '../src/local/coordination.js';
const cleanups: LocalCoordination[] = [];
afterEach(() => { cleanups.splice(0).forEach(s => s.close()); });
function fixture(lookup = 0, timeout = 20000) { const repo = new InMemoryOperationsRepository(); seedLocal(repo); const service = new LocalCoordination(repo, lookup, timeout); cleanups.push(service); return { repo, service }; }
const request = 'transport Bed 18 to Radiology by wheelchair';
const create = async (s: LocalCoordination, id = randomUUID()) => { await s.command(id, 1, request); return (await s.state()).tasks[0]!; };
describe('explicit local coordination', () => {
  it('saves before reporting, waits for a human simulation action, and returns the same state', async () => { const { service, repo } = fixture(); const t = await create(service); expect(t.status).toBe('assigned'); expect(repo.tasks.size).toBe(1); await service.action(t.id, t.assignedStaffId!, 'accept'); expect((await service.state()).tasks[0]?.status).toBe('accepted'); });
  it('discards late Bed 18 lookup and acts only on Bed 21', async () => { const { service, repo } = fixture(20); const id = randomUUID(); const old = service.command(id, 1, request); const assertion = expect(old).rejects.toThrow('STALE_OPERATION'); const next = service.command(id, 2, 'cancel, Bed 21 instead'); await assertion; await next; expect([...repo.tasks.values()].map(t => t.bedId)).toEqual([bedId(21)]); expect(repo.events.some(e => e.type === 'lookup.stale_discarded')).toBe(true); });
  it('stop before dispatch leaves no task', async () => { const { service, repo } = fixture(10); const id = randomUUID(); const old = service.command(id, 1, request); service.interrupt(id, 2); await expect(old).rejects.toThrow('STALE_OPERATION'); expect(repo.tasks.size).toBe(0); });
  it('requires acknowledgement after dispatch, and rejects late acceptance', async () => { const { service, repo } = fixture(); const t = await create(service); await service.action(t.id, NURSE, 'cancel'); expect(repo.tasks.get(t.id)?.status).toBe('cancellation_requested'); await expect(service.action(t.id, t.assignedStaffId!, 'accept')).rejects.toThrow(); await service.action(t.id, t.assignedStaffId!, 'ack_cancel'); expect(repo.tasks.get(t.id)?.status).toBe('cancelled'); });
  it('keeps cancellation pending when replacing a dispatched request', async () => { const { service, repo } = fixture(); const id = randomUUID(); const t = await create(service, id); await service.command(id, 2, 'cancel, Bed 21 instead'); expect(repo.tasks.get(t.id)?.status).toBe('cancellation_requested'); expect([...repo.tasks.values()].find(t => t.bedId === bedId(21))?.status).toBe('assigned'); });
  it('deduplicates concurrent requests and refuses conflicting destinations', async () => { const { service, repo } = fixture(); await Promise.all([service.command(randomUUID(), 1, request), service.command(randomUUID(), 1, request)]); expect(repo.tasks.size).toBe(1); await expect(service.command(randomUUID(), 1, 'transport Bed 18 to Pharmacy by stretcher')).rejects.toThrow('Existing task'); expect([...repo.tasks.values()][0]?.destination).toBe('Radiology'); });
  it('only the offered worker can accept, including concurrent responses', async () => { const { service, repo } = fixture(); const t = await create(service); const outcomes = await Promise.allSettled([service.action(t.id, t.assignedStaffId!, 'accept'), service.action(t.id, bedId(3), 'accept')]); expect(outcomes.map(r => r.status)).toEqual(['fulfilled', 'rejected']); expect(repo.tasks.get(t.id)?.assignedStaffId).toBe(t.assignedStaffId); });
  it('rejection tries the next worker', async () => { const { service, repo } = fixture(); const t = await create(service); await service.action(t.id, t.assignedStaffId!, 'reject'); expect(repo.tasks.get(t.id)?.assignedStaffId).toBe(bedId(3)); });
  it('timeout exhausts workers and records a coordinator alert', async () => { const { service, repo } = fixture(0, 15); const t = await create(service); await new Promise(r => setTimeout(r, 65)); expect(repo.tasks.get(t.id)?.status).toBe('failed'); expect(repo.notifications).toHaveLength(1); expect([...repo.attempts.values()].map(a => a.response)).toEqual(['timeout', 'timeout']); });
  it.each(['transport Bed 99 to Radiology', 'transport Bed 22 to Radiology', 'transport Bed 18 to Mars'])('rejects invalid request: %s', async message => { const { service, repo } = fixture(); await expect(service.command(randomUUID(), 1, message)).rejects.toThrow(); expect(repo.tasks.size).toBe(0); });
  it('replays the same operation idempotently and rejects revision reuse', async () => { const { service, repo } = fixture(); const id = randomUUID(); await Promise.all([service.command(id, 1, request), service.command(id, 1, request)]); expect(repo.tasks.size).toBe(1); await expect(service.command(id, 1, 'hello')).rejects.toThrow('Revision already used'); });
  it('completion is idempotent but cannot precede acceptance', async () => { const { service, repo } = fixture(); const t = await create(service); await expect(service.action(t.id, t.assignedStaffId!, 'complete')).rejects.toThrow(); await service.action(t.id, t.assignedStaffId!, 'accept'); await service.action(t.id, t.assignedStaffId!, 'complete'); await service.action(t.id, t.assignedStaffId!, 'complete'); expect(repo.tasks.get(t.id)?.status).toBe('completed'); });
});
